### ISSUE TITLE
Support for custom port

### ISSUE THREAD

**Issue by neidiom** [AntiPhotonltd/ssl_expiry#1]
Love the gem, good work. Is it possible to check the cert on a custom port?

**Comment by TGWolf** [comment]
Hi.

Really glad you like the gem, I will take a look over the weekend and see if this can be extended to do custom ports.

**Comment by TGWolf** [comment]
Right, I have had a look at this and given how the tool works it will require a few changes to make this possible.

instead of passing a domain name (or list of them), you will need to give a domain name and port

eg.

ssl_expiry antiphoton.com would become ssl_expiry antiphoton.com:8080

If there is no port added it will drop back to the default (443)

Hopefully this will give you the functionality you need.

**Comment by TGWolf** [comment]
v1.0.3 is now available with this feature.
